services:
  db:
    image: postgres:17-alpine
    container_name: qualify_db
    environment:
      POSTGRES_USER: gouser
      POSTGRES_PASSWORD: gopassword
      POSTGRES_DB: godb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gouser -d godb"]
      interval: 2s
      timeout: 2s
      retries: 2

  migrate:
    image: migrate/migrate:v4.16.2
    volumes:
      - ./internal/database/migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    command: ["-path", "/migrations", "-database", "postgres://gouser:gopassword@db:5432/godb?sslmode=disable", "up"]

  migrate-cli:
    image: migrate/migrate:v4.16.2
    container_name: qualify_migrate_cli
    volumes:
      - ./internal/database/migrations:/migrations
    profiles:
      - tools
    command: ["-path", "/migrations", "-database", "postgres://gouser:gopassword@db:5432/godb?sslmode=disable"]

  app:
    build: .
    container_name: qualify_app
    ports:
      - "8001:8001"
    environment:
      - DB_URL=postgres://gouser:gopassword@db:5432/godb?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  pgdata: