services:
  db:
    image: postgres:17-alpine
    container_name: qualify_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 2s
      retries: 2

  migrate:
    image: migrate/migrate:v4.16.2
    volumes:
      - ./internal/database/migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    command: ["-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}?sslmode=${DB_SSLMODE}", "up"]

  migrate-cli:
    image: migrate/migrate:v4.16.2
    container_name: qualify_migrate_cli
    volumes:
      - ./internal/database/migrations:/migrations
      - ./internal/database/uploads:/uploads
    profiles:
      - tools
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/migrate", "-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}?sslmode=${DB_SSLMODE}"]
  app:
    build: .
    container_name: qualify_app
    ports:
      - "${OUT_PORT}:${OUT_PORT}"
    environment:
      - DB_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DB_PORT}/${POSTGRES_DB}?sslmode=${DB_SSLMODE}
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  pgdata: